[project]
name = "myriad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["broadlink>=0.19.0", "python-rtmidi>=1.5.8", "rich>=14.0.0"]

[dependency-groups]
dev = [
  "black>=25.1.0",
  "bpython>=0.25",
  "isort>=6.0.1",
  "mypy>=1.16.0",
  "pytest>=8.4.0",
  "pytest-cov>=6.1.1",
  "ruff>=0.11.13",
  "types-pyyaml>=6.0.12.20250516",
]
