[env]
NEOCITIES_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'

[tools]
'gem:neocities' = '0.0.20'

[tasks]
'push' = { run = 'neocities push --prune src/' }
'info' = { run = 'neocities info' }
'pull' = { run = 'neocities pull' }
'browse' = { run = 'open https://daveio.neocities.org' }
