services:
  ntopng:
    build: .
    container_name: ntopng-main
    environment:
      GEOIPUPDATE_DB_DIR: /usr/share/GeoIP
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country GeoLite2-City GeoLite2-ASN
      GEOIPUPDATE_VERBOSE: '1'
      # REMOTE_REDIS: redis:6379
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3000/lua/rest/v2/get/system/stats.lua
      timeout: 10s
    ports:
      - 3000:3000
      - 2055:2055/udp
      - 8080:8080
      - 6379:6379
    restart: unless-stopped
    volumes:
      - ./ntopng-lib:/var/lib/ntopng
      - ./ntopng-run:/var/run/ntopng
      - ./ntopng-logs:/var/log/ntopng
